name = "codeer-org"
compatibility_date = "2025-04-16"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[env.production]
workers_dev = false

[env.development]
workers_dev = true
